package com.example.repository

import com.example.models.ApiResponse
import com.example.models.QuestionWord
import org.koin.core.qualifier.qualifier
import kotlin.random.Random

class HeroRepositoryImpl:HeroRepository {

    override val heroes: Map<Int, List<QuestionWord>> by lazy {
        mapOf(
            1 to page1,
            2 to page2,
            3 to page3,
        )
    }

    override val page1 = listOf(
        QuestionWord(1, "Elma", "Apple", 1),
        QuestionWord(2, "Kapı", "Door", 1),
        QuestionWord(3, "Kitap", "Book", 1),
        QuestionWord(4, "Kalem", "Pen", 1),
        QuestionWord(5, "Masa", "Desk", 1),
        QuestionWord(6, "Bilgisayar", "Computer", 1),
        QuestionWord(7, "Telefon", "Phone", 1),
        QuestionWord(8, "Anahtar", "Key", 1),
        QuestionWord(9, "Sandalye", "Chair", 1),
        QuestionWord(10, "Saat", "Clock", 1),
        QuestionWord(11, "Araba", "Car", 1),
        QuestionWord(12, "Televizyon", "Television", 1),
        QuestionWord(13, "Duvar", "Wall", 1),
        QuestionWord(14, "Bardak", "Cup", 1),
        QuestionWord(15, "Kedi", "Cat", 1),
        QuestionWord(16, "Köpek", "Dog", 1),
        QuestionWord(17, "Yatak", "Bed", 1),
        QuestionWord(18, "Kalemlik", "Pencil case", 1),
        QuestionWord(19, "Küvet", "Bathtub", 1),
        QuestionWord(20, "Ayna", "Mirror", 1),
        QuestionWord(21, "Perde", "Curtain", 1),
        QuestionWord(22, "Çanta", "Bag", 1),
        QuestionWord(23, "Kart", "Card", 1),
        QuestionWord(24, "Yastık", "Pillow", 1),
        QuestionWord(25, "Kapşon", "Hood", 1),
        QuestionWord(26, "Kırmızı", "Red", 1),
        QuestionWord(27, "Mavi", "Blue", 1),
        QuestionWord(28, "Yeşil", "Green", 1),
        QuestionWord(29, "Sarı", "Yellow", 1),
        QuestionWord(30, "Siyah", "Black", 1),
        QuestionWord(31, "Beyaz", "White", 1),
        QuestionWord(32, "Gri", "Gray", 1),
        QuestionWord(33, "Pembe", "Pink", 1),
        QuestionWord(34, "Turuncu", "Orange", 1),
        QuestionWord(35, "Mor", "Purple", 1),
        QuestionWord(36, "Kahverengi", "Brown", 1),
        QuestionWord(37, "Altın", "Gold", 1),
        QuestionWord(38, "Gümüş", "Silver", 1),
        QuestionWord(39, "Çiçek", "Flower", 1),
        QuestionWord(40, "Ağaç", "Tree", 1),
        QuestionWord(41, "Kuş", "Bird", 1),
        QuestionWord(42, "Balık", "Fish", 1),
        QuestionWord(43, "At", "Horse", 1),
        QuestionWord(44, "Fil", "Elephant", 1),
        QuestionWord(45, "Aslan", "Lion", 1),
        QuestionWord(46, "Köpekbalığı", "Shark", 1),
        QuestionWord(47, "Uçak", "Plane", 1),
        QuestionWord(48, "Gem", "Ship", 1),
        QuestionWord(49, "Tren", "Train", 1),
        QuestionWord(50, "Bisiklet", "Bicycle", 1),
        QuestionWord(51, "Helikopter", "Helicopter", 1),
        QuestionWord(52, "Otobüs", "Bus", 1),
        QuestionWord(53, "Otoban", "Highway", 1),
        QuestionWord(54, "Kaplan", "Tiger", 1),
        QuestionWord(55, "Köpekbalığı", "Shark", 1),
        QuestionWord(56, "Karga", "Crow", 1),
        QuestionWord(57, "Böcek", "Bug", 1),
        QuestionWord(58, "Salyangoz", "Snail", 1),
        QuestionWord(59, "Kertenkele", "Lizard", 1),
        QuestionWord(60, "Yılan", "Snake", 1),
        QuestionWord(61, "Fare", "Mouse", 1),
        QuestionWord(62, "Kaplumbağa", "Turtle", 1),
        QuestionWord(63, "Kurt", "Wolf", 1),
        QuestionWord(64, "Kuzu", "Lamb", 1),
        QuestionWord(65, "Kuş", "Bird", 1),
        QuestionWord(66, "Kelebek", "Butterfly", 1),
        QuestionWord(67, "Arı", "Bee", 1),
        QuestionWord(68, "Karınca", "Ant", 1),
        QuestionWord(69, "Örümcek", "Spider", 1),
        QuestionWord(70, "Kurbağa", "Frog", 1),
        QuestionWord(71, "Bal", "Honey", 1),
        QuestionWord(72, "Süt", "Milk", 1),
        QuestionWord(73, "Pasta", "Cake", 1),
        QuestionWord(74, "Çikolata", "Chocolate", 1),
        QuestionWord(75, "Reçel", "Jam", 1),
        QuestionWord(76, "Ekmek", "Bread", 1),
        QuestionWord(77, "Pirinç", "Rice", 1),
        QuestionWord(78, "Makarna", "Pasta", 1),
        QuestionWord(79, "Salata", "Salad", 1),
        QuestionWord(80, "Pizza", "Pizza", 1),
        QuestionWord(81, "Hamburger", "Hamburger", 1),
        QuestionWord(82, "Sandviç", "Sandwich", 1),
        QuestionWord(83, "Çorba", "Soup", 1),
        QuestionWord(84, "Kahve", "Coffee", 1),
        QuestionWord(85, "Çay", "Tea", 1),
        QuestionWord(86, "Su", "Water", 1),
        QuestionWord(87, "Meyve", "Fruit", 1),
        QuestionWord(88, "Sebze", "Vegetable", 1),
        QuestionWord(89, "Pilav", "Pilaf", 1),
        QuestionWord(90, "Yoğurt", "Yogurt", 1),
        QuestionWord(91, "Tavuk", "Chicken", 1),
        QuestionWord(92, "Balık", "Fish", 1),
        QuestionWord(93, "Et", "Meat", 1),
        QuestionWord(94, "Pilav", "Rice", 1),
        QuestionWord(95, "Makarna", "Noodle", 1),
        QuestionWord(96, "Omlet", "Omelette", 1),
        QuestionWord(97, "Patates", "Potato", 1),
        QuestionWord(98, "Havuç", "Carrot", 1),
        QuestionWord(99, "Soğan", "Onion", 1),
        QuestionWord(100, "Domates", "Tomato", 1)
    )

    override val page2 = listOf(
        QuestionWord(1, "Gökyüzü", "Sky", 3),
        QuestionWord(2, "Okyanus", "Ocean", 3),
        QuestionWord(3, "Bulut", "Cloud", 3),
        QuestionWord(4, "Dünya", "Earth", 3),
        QuestionWord(5, "Güneş", "Sun", 3),
        QuestionWord(6, "Ay", "Moon", 3),
        QuestionWord(7, "Yıldız", "Star", 3),
        QuestionWord(8, "Gezegen", "Planet", 3),
        QuestionWord(9, "Evren", "Universe", 3),
        QuestionWord(10, "Galaksi", "Galaxy", 3),
        QuestionWord(11, "Uzay", "Space", 3),
        QuestionWord(12, "Yıldırım", "Lightning", 3),
        QuestionWord(13, "Deprem", "Earthquake", 3),
        QuestionWord(14, "Fırtına", "Storm", 3),
        QuestionWord(15, "Gökkuşağı", "Rainbow", 3),
        QuestionWord(16, "Yıldırım", "Thunder", 3),
        QuestionWord(17, "Rüzgar", "Wind", 3),
        QuestionWord(18, "Yelken", "Sail", 3),
        QuestionWord(19, "Dalgalar", "Waves", 3),
        QuestionWord(20, "Günbatımı", "Sunset", 3),
        QuestionWord(21, "Gündoğumu", "Sunrise", 3),
        QuestionWord(22, "Çiçekler", "Flowers", 3),
        QuestionWord(23, "Bahar", "Spring", 3),
        QuestionWord(24, "Yaz", "Summer", 3),
        QuestionWord(25, "Sonbahar", "Autumn", 3),
        QuestionWord(26, "Kış", "Winter", 3),
        QuestionWord(27, "Kar", "Snow", 3),
        QuestionWord(28, "Buz", "Ice", 3),
        QuestionWord(29, "Maden", "Mine", 3),
        QuestionWord(30, "Altın", "Gold", 3),
        QuestionWord(31, "Gümüş", "Silver", 3),
        QuestionWord(32, "Demir", "Iron", 3),
        QuestionWord(33, "Elmas", "Diamond", 3),
        QuestionWord(34, "Çelik", "Steel", 3),
        QuestionWord(35, "Bronz", "Bronze", 3),
        QuestionWord(36, "Kurşun", "Lead", 3),
        QuestionWord(37, "Bakır", "Copper", 3),
        QuestionWord(38, "Platin", "Platinum", 3),
        QuestionWord(39, "Mermer", "Marble", 3),
        QuestionWord(40, "Taş", "Stone", 3),
        QuestionWord(41, "Kum", "Sand", 3),
        QuestionWord(42, "Toprak", "Soil", 3),
        QuestionWord(43, "Çakıl", "Pebble", 3),
        QuestionWord(44, "Tuğla", "Brick", 3),
        QuestionWord(45, "Sünger", "Sponge", 3),
        QuestionWord(46, "Ağaç", "Tree", 3),
        QuestionWord(47, "Çalı", "Bush", 3),
        QuestionWord(48, "Çimen", "Grass", 3),
        QuestionWord(49, "Çiçek", "Flower", 3),
        QuestionWord(50, "Tomurcuk", "Bud", 3),
        QuestionWord(51, "Dallar", "Branches", 3),
        QuestionWord(52, "Yapraklar", "Leaves", 3),
        QuestionWord(53, "Kökler", "Roots", 3),
        QuestionWord(54, "Dikim", "Planting", 3),
        QuestionWord(55, "Büyüme", "Growth", 3),
        QuestionWord(56, "Hasat", "Harvest", 3),
        QuestionWord(57, "Tohum", "Seed", 3),
        QuestionWord(58, "Çiçek", "Blossom", 3),
        QuestionWord(59, "Polen", "Pollen", 3),
        QuestionWord(60, "Meyve", "Fruit", 3),
        QuestionWord(61, "Sebze", "Vegetable", 3),
        QuestionWord(62, "Narenciye", "Citrus", 3),
        QuestionWord(63, "Elma", "Apple", 3),
        QuestionWord(64, "Armut", "Pear", 3),
        QuestionWord(65, "Portakal", "Orange", 3),
        QuestionWord(66, "Mandalina", "Tangerine", 3),
        QuestionWord(67, "Greyfurt", "Grapefruit", 3),
        QuestionWord(68, "Limon", "Lemon", 3),
        QuestionWord(69, "Kivi", "Kiwi", 3),
        QuestionWord(70, "Muz", "Banana", 3),
        QuestionWord(71, "Çilek", "Strawberry", 3),
        QuestionWord(72, "Kiraz", "Cherry", 3),
        QuestionWord(73, "Üzüm", "Grape", 3),
        QuestionWord(74, "Ananas", "Pineapple", 3),
        QuestionWord(75, "Kavun", "Melon", 3),
        QuestionWord(76, "Karpuz", "Watermelon", 3),
        QuestionWord(77, "Ayva", "Quince", 3),
        QuestionWord(78, "İncir", "Fig", 3),
        QuestionWord(79, "Kestane", "Chestnut", 3),
        QuestionWord(80, "Badem", "Almond", 3),
        QuestionWord(81, "Fındık", "Hazelnut", 3),
        QuestionWord(82, "Ceviz", "Walnut", 3),
        QuestionWord(83, "Susam", "Sesame", 3),
        QuestionWord(84, "Ayçekirdeği", "Sunflower seed", 3),
        QuestionWord(85, "Düzlem", "Plain", 3),
        QuestionWord(86, "Dağ", "Mountain", 3),
        QuestionWord(87, "Tepe", "Hill", 3),
        QuestionWord(88, "Vadi", "Valley", 3),
        QuestionWord(89, "Vulkan", "Volcano", 3),
        QuestionWord(90, "Uçurum", "Cliff", 3),
        QuestionWord(91, "Kanyon", "Canyon", 3),
        QuestionWord(92, "Ova", "Field", 3),
        QuestionWord(93, "Mera", "Pasture", 3),
        QuestionWord(94, "Orman", "Forest", 3),
        QuestionWord(95, "Çöl", "Desert", 3),
        QuestionWord(96, "Deniz", "Sea", 3),
        QuestionWord(97, "Göl", "Lake", 3),
        QuestionWord(98, "Nehir", "River", 3),
        QuestionWord(99, "Baraj", "Dam", 3),
        QuestionWord(100, "Şelale", "Waterfall", 3)
    )

    override val page3 = listOf(
        QuestionWord(1, "Metamorfoz", "Metamorphosis", 5),
        QuestionWord(2, "Antidepresan", "Antidepressant", 5),
        QuestionWord(3, "Nükleer", "Nuclear", 5),
        QuestionWord(4, "Biyojenik", "Biogenic", 5),
        QuestionWord(5, "Elektrifikasyon", "Electrification", 5),
        QuestionWord(6, "Magnetometre", "Magnetometer", 5),
        QuestionWord(7, "Kristalografi", "Crystallography", 5),
        QuestionWord(8, "Akreditasyon", "Accreditation", 5),
        QuestionWord(9, "Entomoloji", "Entomology", 5),
        QuestionWord(10, "Myrmecology", "Myrmecology", 5),
        QuestionWord(11, "Xenofobi", "Xenophobia", 5),
        QuestionWord(12, "Zoonoz", "Zoonosis", 5),
        QuestionWord(13, "Paradigmatik", "Paradigmatic", 5),
        QuestionWord(14, "Biyogeokimya", "Biogeochemistry", 5),
        QuestionWord(15, "Kronoloji", "Chronology", 5),
        QuestionWord(16, "Anomalistik", "Anomalistic", 5),
        QuestionWord(17, "Monogami", "Monogamy", 5),
        QuestionWord(18, "Polygami", "Polygamy", 5),
        QuestionWord(19, "Makroekonomi", "Macroeconomics", 5),
        QuestionWord(20, "Mikroekonomi", "Microeconomics", 5),
        QuestionWord(21, "Ekstrakorporal", "Extracorporeal", 5),
        QuestionWord(22, "Pandemik", "Pandemic", 5),
        QuestionWord(23, "Endemik", "Endemic", 5),
        QuestionWord(24, "Epistemoloji", "Epistemology", 5),
        QuestionWord(25, "Aritmetik", "Arithmetic", 5),
        QuestionWord(26, "Geometri", "Geometry", 5),
        QuestionWord(27, "Trigonometri", "Trigonometry", 5),
        QuestionWord(28, "Kozmoloji", "Cosmology", 5),
        QuestionWord(29, "Nörofizyoloji", "Neurophysiology", 5),
        QuestionWord(30, "Fizyoterapi", "Physiotherapy", 5),
        QuestionWord(31, "Hidrojenasyon", "Hydrogenation", 5),
        QuestionWord(32, "Elektroforez", "Electrophoresis", 5),
        QuestionWord(33, "Gastroenteroloji", "Gastroenterology", 5),
        QuestionWord(34, "Patoloji", "Pathology", 5),
        QuestionWord(35, "Farmakoloji", "Pharmacology", 5),
        QuestionWord(36, "Epizotoloji", "Epidemiology", 5),
        QuestionWord(37, "Biokimya", "Biochemistry", 5),
        QuestionWord(38, "Antikor", "Antibody", 5),
        QuestionWord(39, "Nörotransmiter", "Neurotransmitter", 5),
        QuestionWord(40, "Mikrobiyoloji", "Microbiology", 5),
        QuestionWord(41, "Parazitoloji", "Parasitology", 5),
        QuestionWord(42, "Viroloji", "Virology", 5),
        QuestionWord(43, "Ergonomi", "Ergonomics", 5),
        QuestionWord(44, "Ekvator", "Equator", 5),
        QuestionWord(45, "Polarizasyon", "Polarization", 5),
        QuestionWord(46, "Aksiyon", "Action", 5),
        QuestionWord(47, "Reaksiyon", "Reaction", 5),
        QuestionWord(48, "Kataliz", "Catalysis", 5),
        QuestionWord(49, "Oksidasyon", "Oxidation", 5),
        QuestionWord(50, "Redüksiyon", "Reduction", 5),
        QuestionWord(51, "Enerji", "Energy", 5),
        QuestionWord(52, "Entropi", "Entropy", 5),
        QuestionWord(53, "Termodinamik", "Thermodynamics", 5),
        QuestionWord(54, "Elektrik", "Electricity", 5),
        QuestionWord(55, "Manyetizma", "Magnetism", 5),
        QuestionWord(56, "Optik", "Optics", 5),
        QuestionWord(57, "Akustik", "Acoustics", 5),
        QuestionWord(58, "Radyasyon", "Radiation", 5),
        QuestionWord(59, "Kuantum", "Quantum", 5),
        QuestionWord(60, "Nükleer", "Nuclear", 5),
        QuestionWord(61, "Biyoloji", "Biology", 5),
        QuestionWord(62, "Genetik", "Genetics", 5),
        QuestionWord(63, "Hücre", "Cell", 5),
        QuestionWord(64, "Organizma", "Organism", 5),
        QuestionWord(65, "Evrim", "Evolution", 5),
        QuestionWord(66, "Ekosistem", "Ecosystem", 5),
        QuestionWord(67, "Biyosfer", "Biosphere", 5),
        QuestionWord(68, "Habitat", "Habitat", 5),
        QuestionWord(69, "Biyoteknoloji", "Biotechnology", 5),
        QuestionWord(70, "Nanoteknoloji", "Nanotechnology", 5),
        QuestionWord(71, "Endüstriyel", "Industrial", 5),
        QuestionWord(72, "Organik", "Organic", 5),
        QuestionWord(73, "Sentetik", "Synthetic", 5),
        QuestionWord(74, "Fiziksel", "Physical", 5),
        QuestionWord(75, "Kimyasal", "Chemical", 5),
        QuestionWord(76, "Biyo", "Bio", 5),
        QuestionWord(77, "Oto", "Auto", 5),
        QuestionWord(78, "Mekanik", "Mechanical", 5),
        QuestionWord(79, "Elektronik", "Electronic", 5),
        QuestionWord(80, "Optik", "Optical", 5),
        QuestionWord(81, "Termal", "Thermal", 5),
        QuestionWord(82, "Hidrolik", "Hydraulic", 5),
        QuestionWord(83, "Pnömatik", "Pneumatic", 5),
        QuestionWord(84, "Termoelektrik", "Thermoelectric", 5),
        QuestionWord(85, "Akustik", "Acoustic", 5),
        QuestionWord(86, "Astronomi", "Astronomy", 5),
        QuestionWord(87, "Astrofizik", "Astrophysics", 5),
        QuestionWord(88, "Kozmik", "Cosmic", 5),
        QuestionWord(89, "Meteoroloji", "Meteorology", 5),
        QuestionWord(90, "Klimatoloji", "Climatology", 5),
        QuestionWord(91, "Gazlar", "Gases", 5),
        QuestionWord(92, "Sıvılar", "Liquids", 5),
        QuestionWord(93, "Katılar", "Solids", 5),
        QuestionWord(94, "Plazma", "Plasma", 5),
        QuestionWord(95, "Yoğunlaşma", "Condensation", 5),
        QuestionWord(96, "Buharlaşma", "Evaporation", 5),
        QuestionWord(97, "Yoğunluk", "Density", 5),
        QuestionWord(98, "Basınç", "Pressure", 5),
        QuestionWord(99, "Hacim", "Volume", 5),
        QuestionWord(100, "Sıcaklık", "Temperature", 5)
    )


    override suspend fun getQuestion(): ApiResponse {
        var randomIndex = List(3) {Random.nextInt(0,101)}
        var randomIndexList:MutableList<QuestionWord> = mutableListOf()

        for(a in randomIndex){
            var question = page1[a]
            randomIndexList.add(question)
        }
        return  ApiResponse(randomIndexList)
    }

    override suspend fun getQuestionMedium(): ApiResponse {
        var randomIndex = List(3) {Random.nextInt(0,101)}
        var randomIndexList:MutableList<QuestionWord> = mutableListOf()

        for(a in randomIndex){
            var question = page2[a]
            randomIndexList.add(question)
        }
        return  ApiResponse(randomIndexList)
    }

    override suspend fun getQuestionHard(): ApiResponse {
        var randomIndex = List(3) {Random.nextInt(0,101)}
        var randomIndexList:MutableList<QuestionWord> = mutableListOf()

        for(a in randomIndex){
            var question = page3[a]
            randomIndexList.add(question)
        }
        return  ApiResponse(randomIndexList)
    }

}